### PR TITLE
Read Kubeconfig path from env on priority.

### LINKED ISSUE #45: KUBECONFIG environment variable should be respected
**Describe the bug**

All "standard" kubectl-like clients respect the KUBECONFIG environment variable, but `kor` does not use it, defaulting to `~/.kube/config`.

**To Reproduce**

```
$ rm ~/.kube/config  # :trollface: - it's my default since I think having multiple dev+prod contexts in one central file is dangerous

$ export KUBECONFIG="${HOME}/.kube/config-some-other-file"

$ kor secret -n kube-system
Failed to load kubeconfig: stat /Users/myname/.kube/config: no such file or directory
```

**Expected behavior**

Respect the environment variable and don't explicitly require `--kubeconfig "$KUBECONFIG"`. If `--kubeconfig` is set though, that argument should have higher priority (as with other clients).

**OS version, architecture and kor version**

macOS Ventura 13.5, arm64
Kor version: 0.1.8

### PR DESCRIPTION
**Pull request by rameshgkwd05**
This PR aims to read Kubeconfig path from environment first and as fallback uses default location.
Methods having only local use are kept/made local.
The unite tests are added to cover newly added code.
fixes #45

### CODE REVIEW

**Comment by AndiDog** [comment]
The CLI parameter (`rootCmd.PersistentFlags().StringVarP(&kubeconfig, "kubeconfig", "k", "", "Path to kubeconfig file (optional)")`) must always take precedence, then environment, then the default path.

File: pkg/kor/kor.go [hunk 1]
```diff
@@ -33,16 +33,26 @@ func RemoveDuplicatesAndSort(slice []string) []string {
...
+		} else {
+			kubeconfig = getDefaultKubeConfigPath()
+		}
 	}
-	config, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
+	return kubeconfig
+}
+
+func GetKubeClient(kubeconfig string) *kubernetes.Clientset {
+	kubeconfigPath := loadOrGetKubeConfigPath(kubeconfig)
```
Comment (yonahd) [inline pkg/kor/kor.go:53]: No need for the additional function.
The if else can be done in the original function

**Comment by yonahd** [comment]
> The CLI parameter (`rootCmd.PersistentFlags().StringVarP(&kubeconfig, "kubeconfig", "k", "", "Path to kubeconfig file (optional)")`) must always take precedence, then environment, then the default path.

Yep. This is done by checking if the value of the flag is empty

**Comment by AndiDog** [comment]
> > The CLI parameter (`rootCmd.PersistentFlags().StringVarP(&kubeconfig, "kubeconfig", "k", "", "Path to kubeconfig file (optional)")`) must always take precedence, then environment, then the default path.
> 
> Yep. This is done by checking if the value of the flag is empty

Thanks. I wasn't exactly sure from the PR title and by taking a very short look. Change looks good!

**Comment by yonahd** [comment]
@rameshgkwd05 Do you intend to complete this MR?
I would like to put it in the upcoming release

**Comment by rameshgkwd05** [comment]
> @rameshgkwd05 Do you intend to complete this MR? I would like to put it in the upcoming release
Yes @yonahd I would address review comments and make it review ready

File: pkg/kor/kor.go (hunk 1 above)
Comment (rameshgkwd05) [reply pkg/kor/kor.go]: addressed this

File: pkg/kor/kor_test.go [hunk 2]
```diff
@@ -60,3 +61,62 @@ func TestCalculateResourceDifference(t *testing.T) {
...
+    cluster: foo-cluster
+    namespace: bar
+  name: foo-context
+current-context: foo-context
+kind: Config
+`
+	return fakeContent
+}
+
+func TestGetKubeClient_fromEnvVar(t *testing.T) {
```
Comment (yonahd) [inline pkg/kor/kor_test.go:88]: Please rename the function to use camelCase

File: pkg/kor/kor_test.go [hunk 3]
```diff
@@ -60,3 +61,62 @@ func TestCalculateResourceDifference(t *testing.T) {
...
+	defer os.Setenv("KUBECONFIG", originalKCEnv)
+	os.Setenv("KUBECONFIG", configFile.Name())
+
+	kcs := GetKubeClient("")
+	if kcs == nil {
+		t.Errorf("Expected valid clientSet")
+	}
+}
+
+func TestGetKubeClient_fromInput(t *testing.T) {
```
Comment (yonahd) [inline pkg/kor/kor_test.go:108]: Please rename the function to use camelCase

**Review by yonahd — COMMENTED** [review]
@rameshgkwd05 Looks good.
A couple of small comments

File: pkg/kor/kor_test.go (hunk 2 above)
Comment (rameshgkwd05) [reply pkg/kor/kor_test.go]: done

File: pkg/kor/kor_test.go (hunk 3 above)
Comment (rameshgkwd05) [reply pkg/kor/kor_test.go]: done

**Review by yonahd — APPROVED** [review]
LGTM
