### PR TITLE
fix(GetUnusedAll): skip non-namespaced resources if --include-namespaces flag is used

### LINKED ISSUE #178: kor all -n displays non namespaced resources
**Describe the bug**
kor all -n displays non namespaced resources

**To Reproduce**
"have non namspaced orphaned recources like CRD's in your cluster" 
kor all -n default

**Expected behavior**
when i specify explicit Namespaces, i want to ONLY have the resources in those namespaces evaluated.

**Screenshots**
wouldnt help as the issue seems clear

**OS version, architecture and kor version**
Linux x86_64
Kor version: 0.3.2

### PR DESCRIPTION
**Pull request by doronkg**
## What this PR does / why we need it

Currently, when running `kor all -n example`, unused non-namespaced resources will be displayed as well.
This PR fixes `GetUnusedAll()` function to skip non-namespaced resources if `--include-namespaces` flag is used.
`--include-namespaces` flag is considered used if the amount of listed namespaces is greater than 0.

In addition, this PR fixes flag typos across the code/docs:
- `--include-namespace` -> `--include-namespaces`
- `--exclude-namespace` -> `--exclude-namespaces`

## PR Checklist

- [ ] This PR adds K8s exceptions (false positives)
- [x] This PR adds new code
- [ ] This PR includes test for any new code

## Github Issue

Resolves #178 

## Notes for your reviewers
`README.md` was automatically lintered by IDE, hence newline changes were commited, etc.

### CODE REVIEW

File: cmd/kor/root.go [hunk 1]
```diff
@@ -80,6 +80,6 @@ func addFilterOptionsFlag(cmd *cobra.Command, opts *filters.Options) {
...
 	cmd.PersistentFlags().StringVar(&opts.OlderThan, "older-than", opts.OlderThan, "The minimum age of the resources to be considered unused. This flag cannot be used together with newer-than flag. Example: --older-than=1h2m")
 	cmd.PersistentFlags().StringVar(&opts.IncludeLabels, "include-labels", opts.IncludeLabels, "Selector to filter in, Example: --include-labels key1=value1.(currently supports one label)")
-	cmd.PersistentFlags().StringSliceVar(&opts.ExcludeNamespaces, "exclude-namespaces", opts.ExcludeNamespaces, "Namespaces to be excluded, split by commas. Example: --exclude-namespace ns1,ns2,ns3. If --include-namespace is set, --exclude-namespaces will be ignored.")
-	cmd.PersistentFlags().StringSliceVarP(&opts.IncludeNamespaces, "include-namespaces", "n", opts.IncludeNamespaces, "Namespaces to run on, split by commas. Example: --include-namespace ns1,ns2,ns3. ")
+	cmd.PersistentFlags().StringSliceVar(&opts.ExcludeNamespaces, "exclude-namespaces", opts.ExcludeNamespaces, "Namespaces to be excluded, split by commas. Example: --exclude-namespaces ns1,ns2,ns3. If --include-namespaces is set, --exclude-namespaces will be ignored.")
```
Comment (yonahd) [inline cmd/kor/root.go:83]: From what I see in many tools including kubectl the flags are singular despite supporting plural

**Review by yonahd — COMMENTED** [review]
One comment.
We might want to later also support a flag for including cluster resources but I'm not sure if its needed.

File: cmd/kor/root.go (hunk 1 above)
Comment (doronkg) [reply cmd/kor/root.go:83]: We could make that change in all related flags: include/exclude-labels/namespaces. 
But this would be breaking change (perhaps we could leave the plural for legacy for couple of releases).
Either way, I think it's out-of-scope for this PR that aims to resolve a specific issue, I've made the plural change only in docs references to align them to the existing flags.

**Comment by doronkg** [comment]
> One comment. We might want to later also support a flag for including cluster resources but I'm not sure if its needed.

We can have a follow-up in a discussion or create a backog issue for that.
Like you, I'm not sure if its needed.

**Review by yonahd — APPROVED** [review]
Lgtm
Thanks
