### PR TITLE
fix(delete): Refactor input handling & output display on resource deletion 

### LINKED ISSUE #321: BUG(delete): Unexpected newline error on deletion confirmation
**Describe the bug**
Sometimes when using the `--delete` flag to remove unused resources from the cluster, the following occures:
When user is asked for confirmation, the following error raises when submitted:
```
$ kor sa --delete
Do you want to delete ServiceAccount test in namespace test? (Y/N): Failed to read input: unexpected newline
```

As the input was invalid, the resource **is not deleted**.

**To Reproduce**
Use `--delete` flag to remove resources and submit confirmation input.

**Expected behavior**
The input is accepted and `kor` proceeds to resource deletion.

**Screenshots**
```console
$ .\main.exe sa --delete
Do you want to delete ServiceAccount zzz in namespace kube-public? (Y/N): Y
Deleting ServiceAccount zzz in namespace kube-public
Do you want to delete ServiceAccount zzz2 in namespace kube-public? (Y/N): Failed to read input: unexpected newline
Do you want to delete ServiceAccount abc in namespace kube-system? (Y/N): Y
Deleting ServiceAccount abc in namespace kube-system
Do you want to delete ServiceAccount abc in namespace default? (Y/N): Failed to read input: unexpected newline
```
**OS version, architecture and kor version**
e.g. Windows 10
Kor version: 0.5.1

**Additional context**

### LINKED ISSUE #322: BUG(delete): "-DELETED" suffix is not added in deletion output
**Describe the bug**
When using the `--delete` flag to remove unused resources, and running it successfully, the output displays all the unused resources the batch prior to the deletion, instead of appending `-DELETED` suffix to their names upon deletion.

**To Reproduce**
Use --delete flag to remove resources review deletion output.

**Expected behavior**
The `-DELETED` suffix will be appended to the deleted resources' names upon deletion and be displayed in output.

**Screenshots**
```console
$ .\main.exe clusterrole --delete
Do you want to delete ClusterRole aaa in namespace ? (Y/N): Y
Deleting ClusterRole aaa in namespace
kor version: vdev

  _  _____  ____
 | |/ / _ \|  _ \
 | ' / | | | |_) |
 | . \ |_| |  _ <
 |_|\_\___/|_| \_\

Unused resources in namespace: ""
+---+---------------+---------------+
| # | RESOURCE TYPE | RESOURCE NAME |
+---+---------------+---------------+
| 1 | ClusterRole   | aaa           |
+---+---------------+---------------+
```

**OS version, architecture and kor version**
e.g. Windows 10
Kor version: 0.5.1

**Additional context**

### PR DESCRIPTION
**Pull request by doronkg**
## What this PR does / why we need it?
This PR aims to resolve 2 outputing issues resulting in the `--delete` flag.
1. Avoid the unexpected newline error on confirmation
2. Append `-DELETED` suffix on deleted resources in output

```console
$ .\main.exe clusterrole --delete
Do you want to delete ClusterRole aaa in namespace ? (Y/N): y
Deleting ClusterRole aaa in namespace
kor version: vdev

  _  _____  ____
 | |/ / _ \|  _ \
 | ' / | | | |_) |
 | . \ |_| |  _ <
 |_|\_\___/|_| \_\

Unused resources in namespace: ""
+---+---------------+---------------+
| # | RESOURCE TYPE | RESOURCE NAME |
+---+---------------+---------------+
| 1 | ClusterRole   | aaa-DELETED   |
+---+---------------+---------------+
```

## PR Checklist

- [ ] This PR adds K8s exceptions (false positives)
- [x] This PR adds new code
- [ ] This PR includes tests for new/existing code
- [ ] This PR adds docs

## GitHub Issue

Closes #321
Closes #322 

## Notes for your reviewers
#321 is resolved by consuming the newline character ("\n") and removing it from the input buffer.
#322 is resolved by moving the deletion logic before the grouping logic, so the updated `diff` variable will be used.

### CODE REVIEW

File: pkg/kor/clusterroles.go [hunk 1]
```diff
@@ -191,18 +191,18 @@ func GetUnusedClusterRoles(filterOpts *filters.Options, clientset kubernetes.Int
 	if err != nil {
 		fmt.Fprintf(os.Stderr, "Failed to process cluster role : %v\n", err)
 	}
+	if opts.DeleteFlag {
+		if diff, err = DeleteResource2(diff, clientset, "", "ClusterRole", opts.NoInteractive); err != nil {
```
Comment (yonahd) [inline pkg/kor/clusterroles.go:195]: Not directly related to this PR, but can we rename DeleteResource2 to DeleteResource and remove the old DeleteResource

**Review by yonahd — COMMENTED** [review]
Looks good overall. Small suggestion

**Review by yonahd — APPROVED** [review]
Lgtm
