### PR TITLE
fix(GetUnusedAll) - JSON concatenation

### LINKED ISSUE #226: Bug: kor exporter cannot parse json
**Describe the bug**
kor exporter cannot parse json:
```go run . exporter
Server listening on :8080
collecting unused resources
Error parsing JSON: invalid character '{' after top-level value
```
json output:
```
{
  "test": {
    "ConfigMap": null,
    "DaemonSet": null,
    "Deployment": null,
    "Hpa": [
      "php-apache"
    ],
    "Ingress": [
      "test-ingress-1-work"
    ],
    "Job": null,
    "Pdb": null,
    "Pvc": [
      "myclaim"
    ],
    "ReplicaSet": null,
    "Role": null,
    "Secret": null,
    "Service": [
      "app1-service",
      "app2-service"
    ],
    "ServiceAccount": null,
    "StatefulSet": null
  }
}{
  "": {
    "ClusterRole": [
      "admin",
      "view"
    ],
    "Crd": [
      "thanosrulers.monitoring.coreos.com"
    ],
    "Pv": null,
    "StorageClass": null
  }
}
Error parsing JSON: invalid character '{' after top-level value
```

**To Reproduce**
run ``kor exporter``  or ``kor all -o json`` after #216  ,also happens with ``-n namepsace`` 

**Expected behavior**
```
{
  "": {
    "ClusterRole": [
      "view"
    ],
    "Crd": [
      "thanosrulers.monitoring.coreos.com"
    ],
    "Pv": null
  },
  "test": {
    "ConfigMap": null,
    "DaemonSet": null,
    "Deployment": null,
    "Hpa": [
      "php-apache"
    ],
    "Ingress": [
      "test-ingress-1-work"
    ],
    "Job": null,
    "Pdb": null,
    "Pvc": [
      "myclaim"
    ],
    "ReplicaSet": null,
    "Role": null,
    "Secret": null,
    "Service": [
      "app1-service",
      "app2-service"
    ],
    "ServiceAccount": null,
    "StatefulSet": null
  }
}
```

**OS version, architecture and kor version**
Darwin x86_64
Kor version: 3.6.0 after #216  got merged.

**Additional context**
seems like a problem when creating the JSON for namespaced and non namespaced resources with the new `GetUnusedAll()` which means we also get it when just running kor all -o json.
multi seems to work fine:
```
go run . crd,deploy,svc,storageclass -o json
{
  "": {
    "Crd": [
      "thanosrulers.monitoring.coreos.com"
    ],
    "StorageClass": null
  },
  "default": {
    "Deployment": [
      "test-deployment0"
    ],
    "Service": [
      "alertmanager-example",
      "example-service"
    ]
  },
  "kube-system": {
    "Deployment": null,
    "Service": [
      "docker.io-hostpath"
    ]
  },
  "test": {
    "Deployment": null,
    "Service": [
      "app1-service",
      "app2-service"
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by doronkg**
This PR aims to resolve #226.
Currently when executing `GetUnusedAll()` with JSON format, instead of merging the two lists, it appends them.
This also resolves the `Error parsing JSON: invalid character '{' after top-level value` returned from `kor exporter`.

Before the fix:
```
$ kor all -o json
{
  "test": {
    "ConfigMap": null,
    "DaemonSet": null,
    "Deployment": null,
    "Hpa": [
      "php-apache"
    ],
    "Ingress": [
      "test-ingress-1-work"
    ],
    "Job": null,
    "Pdb": null,
    "Pvc": [
      "myclaim"
    ],
    "ReplicaSet": null,
    "Role": null,
    "Secret": null,
    "Service": [
      "app1-service",
      "app2-service"
    ],
    "ServiceAccount": null,
    "StatefulSet": null
  }
}{
  "": {
    "ClusterRole": [
      "admin",
      "view"
    ],
    "Crd": [
      "thanosrulers.monitoring.coreos.com"
    ],
    "Pv": null,
    "StorageClass": null
  }
}
```

After the fix:
```
$ kor all -o json
{
  "": {
    "ClusterRole": [
      "admin",
      "view"
    ],
    "Crd": [
      "thanosrulers.monitoring.coreos.com"
    ],
    "Pv": null,
    "StorageClass": null
  },
  "test": {
    "ConfigMap": null,
    "DaemonSet": null,
    "Deployment": null,
    "Hpa": [
      "php-apache"
    ],
    "Ingress": [
      "test-ingress-1-work"
    ],
    "Job": null,
    "Pdb": null,
    "Pvc": [
      "myclaim"
    ],
    "ReplicaSet": null,
    "Role": null,
    "Secret": null,
    "Service": [
      "app1-service",
      "app2-service"
    ],
    "ServiceAccount": null,
    "StatefulSet": null
  }
}
```

### CODE REVIEW

File: pkg/kor/all.go [hunk 1]
```diff
@@ -316,7 +316,34 @@ func GetUnusedAll(filterOpts *filters.Options, clientset kubernetes.Interface, a
 		fmt.Printf("err: %v\n", err)
 	}
 
-	unusedAll := unusedAllNamespaced + unusedAllNonNamespaced
+	unusedAll := make(map[string]interface{})
 
-	return unusedAll, nil
+	if outputFormat != "json" {
```
Comment (yonahd) [inline pkg/kor/all.go:321]: We support yaml as a conversion of the json so we'd need to support that in the condition

Comment (doronkg) [reply pkg/kor/all.go:321]: When adding up both YAML results from the two called functions, they are generated separately and aggregated properly, in case of JSON they are not aggregated properly since each result is wrapped under {}.

**Review by yonahd — APPROVED** [review]
LGTM. Thanks!
